FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

# 必要パッケージのインストール（MXE依存も含む）
RUN apt-get update && apt-get install -y \
    build-essential \
    autoconf \
    automake \
    autopoint \
    bash \
    bison \
    bzip2 \
    ca-certificates \
    cmake \
    curl \
    flex \
    g++ \
    g++-multilib \
    gettext \
    git \
    gperf \
    intltool \
    libc6-dev-i386 \
    libclang-dev \
    libgdk-pixbuf2.0-dev \
    libgl-dev \
    libltdl-dev \
    libpcre2-dev \
    libssl-dev \
    libtool \
    libtool-bin \
    libxml-parser-perl \
    lzip \
    make \
    openssl \
    patch \
    perl \
    pkg-config \
    p7zip-full \
    python-is-python3 \
    python3 \
    python3-mako \
    python3-yaml \
    python3-packaging \
    python3-pip \
    python3-pkg-resources \
    python3-setuptools \
    ruby \
    sed \
    sqlite3 \
    unzip \
    wget \
    xz-utils \
    && rm -rf /var/lib/apt/lists/*

# Python モジュール mako
RUN pip3 install mako

# MXE
WORKDIR /opt

RUN git clone https://github.com/mxe/mxe.git

# Qt 6.12.0 の Wine 互換パッチ
COPY patches/qt6-qtbase-2-wine-wcs.patch \
     /opt/mxe/src/qt/qt6/qt6-qtbase-2-wine-wcs.patch

# MXE + Qt6
RUN cd /opt/mxe && \
    make MXE_TARGETS='i686-w64-mingw32.static' \
         qt6-qtbase \
         gcc \
         cmake \
         ffmpeg \
         -j$(nproc)

ENV PATH="/opt/mxe/usr/bin:$PATH"
