name: arm ubuntu Build & Push Qt6 Static Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04-arm

    env:
      IMAGE_NAME: ghcr.io/csreviser/qt6-ubuntu-arm:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
