name: Build and Push Qt6 (Windows ARM) Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # パッケージ push に必要
    env:
      QT_VERSION: 6.9.0
      IMAGE_NAME_VERSIONED: ghcr.io/csreviser/qt6-win-arm:6.9.0
      IMAGE_NAME_LATEST: ghcr.io/csreviser/qt6-win-arm:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -f Dockerfile.win_arm \
            -t $IMAGE_NAME_VERSIONED \
            -t $IMAGE_NAME_LATEST \
            --build-arg QT_VERSION=$QT_VERSION .

      - name: Push Docker image (versioned)
        run: docker push $IMAGE_NAME_VERSIONED

      - name: Push Docker image (latest)
        run: docker push $IMAGE_NAME_LATEST