name: Build MXE 32bit Qt6 Static Docker Image

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/csreviser/qt6-mxe-x86-static
  QT_VERSION: 6.9.0

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.mxe.qt6-32 -t ${{ env.IMAGE_NAME }}:${{ env.QT_VERSION }} .

      - name: Push Docker image to GHCR
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.QT_VERSION }}
