name: Build MXE Qt6 Static Docker Image

on:
  workflow_dispatch:

env:
  QT_VERSION: 6.9.0

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build & Push MXE Qt6 Docker image
        run: |
          # lowercase GitHubユーザー名を取得
          USER=$(echo "$GITHUB_ACTOR" | tr '[:upper:]' '[:lower:]')
          IMAGE="ghcr.io/${USER}/qt6-mxe-static:${QT_VERSION}"

          # Dockerイメージをビルド
          docker build -f Dockerfile.mxe.qt6 -t "$IMAGE" .

          # GHCRへログイン（GITHUB_TOKENでOK）
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin

          # イメージをプッシュ
          docker push "$IMAGE"