name: Build & Push Qt6 Static Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME_VERSIONED: ghcr.io/csreviser/qt6-static:6.9.2-ubuntu22.04
      IMAGE_NAME_LATEST: ghcr.io/csreviser/qt6-static:latest
      QT_VERSION: 6.9.2

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          build-args: |
            QT_VERSION=${{ env.QT_VERSION }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME_VERSIONED }}
            ${{ env.IMAGE_NAME_LATEST }}
