name: Build CS2 ubuntu22 with Qt Static (Docker)

on:
  workflow_dispatch:

env:
  QT_VERSION: 6.10.0
#  IMAGE_NAME: ghcr.io/csreviser/qt6-static:6.10.0-ubuntu22.04

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/csreviser/qt6-static:6.10.0-ubuntu22.04
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone CaptureStream2
        run: |
          git clone https://github.com/CSReviser/CaptureStream2.git
          cd CaptureStream2
          git submodule update --init --recursive

#      - name: Build using Docker container with Qt static
#        run: |
#          docker run --rm \
#            -v ${{ github.workspace }}:/work \
#            -w /work/CaptureStream2 \
#            ${{ env.IMAGE_NAME }} \
#            bash -lc "
#              mkdir -p build && cd build && \
#              /opt/qt6-static/bin/qt-cmake .. -DQT_DEBUG_FIND_PACKAGE=ON && \
#              cmake --build . --parallel
#            "

      - name: Build using Docker container with Qt static
        run: |
          cd CaptureStream2
          mkdir -p build && cd build
          /opt/qt6-static/bin/qt-cmake .. -DQT_DEBUG_FIND_PACKAGE=ON
          cmake --build . --parallel
          mkdir -p LinCaptureStream2
          mv CaptureStream2 ./LinCaptureStream2/
          cp ../qss_files/stylesheet-ubu.qss ./LinCaptureStream2
          cp -r ../qss_files/License ./LinCaptureStream2
          wget -qO ffmpeg-static-ubuntu.zip https://github.com/CSReviser/ffmpeg-build/releases/download/7.1.1/ffmpeg-static-ubuntu.zip
          7z e ffmpeg-static-ubuntu.zip ffmpeg -o./LinCaptureStream2
          chmod -R 755 ./LinCaptureStream2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: capturestream2-linux-static
          path: CaptureStream2/build/LinCaptureStream2
