name: Init GHCR Package

on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-22.04

    env:
      IMAGE_NAME: ghcr.io/csreviser/qt6-mxe-static:init
      IMAGE: ghcr.io/csreviser/qt6-mxe-static:init

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push dummy Docker image
        run: |
          docker build -f Dockerfile.ghcr-init -t "$IMAGE" .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
