name: test Build & Push Qt6 Static Docker Image (Ubuntu)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME_VERSIONED: ghcr.io/csreviser/test:6.9.0-ubuntu22.04
      IMAGE_NAME_LATEST: ghcr.io/csreviser/test:latest
      QT_VERSION: 6.9.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.test
          build-args: |
            QT_VERSION=${{ env.QT_VERSION }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME_VERSIONED }}
            ${{ env.IMAGE_NAME_LATEST }