name: arm ubuntu22 Build & Push Qt6 Static Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04-arm

    env:
      IMAGE_NAME_VERSIONED: ghcr.io/csreviser/qt6-static-arm:6.9.2-ubuntu22.04
      IMAGE_NAME_LATEST: ghcr.io/csreviser/qt6-static-arm:latest
      QT_VERSION: 6.9.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.ubuntu-arm
          build-args: |
            QT_VERSION=${{ env.QT_VERSION }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME_VERSIONED }}
            ${{ env.IMAGE_NAME_LATEST }}

      - name: Upload CMakeError.log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cmake-error-log
          path: /path/to/qt_build/CMakeFiles/CMakeError.log
